FROM debian:latest
RUN apt-get update && \
    apt-get install -y apt-transport-https curl deb && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    cat <<EOF >/etc/apt/sources.list.d/kubernetes.list \
    deb http://apt.kubernetes.io/ kubernetes-xenial main \
EOF && \ 
    apt-get update && \
    apt-get install -y \
# Install docker if you don't have it already.
    docker-engine \
    curl \
    kubelet \
    kubeadm \
    kubectl \
    kubernetes-cni
