#!/bin/bash

# The execution log can be found on the cloud at /var/log/cloud-init-output.log

sudo mkdir -p /var/cache/kubernetes
sudo apt-get update && sudo apt-get install -y apt-transport-https
sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo bash -c "cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF"
sudo apt-get update
# Install docker if you don't have it already.
sudo apt-get install -y docker-engine
sudo apt-get install -y kubelet kubeadm kubectl kubernetes-cni

sudo kubeadm init --token 294e75.c72dc64fbe863ebf

#Return as normal user and do this.. This ideally should be in .profile
sudo cp /etc/kubernetes/admin.conf $HOME/
sudo chown $(id -u):$(id -g) /home/$LOGNAME/admin.conf
export KUBECONFIG=$HOME/admin.conf

kubectl apply -f https://git.io/weave-kube-1.6

kubectl --kubeconfig /home/$LOGNAME/admin.conf get pods --all-namespaces -o wide

